//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXERCISE_TABLE
    {
        public int EXERCISE_ID { get; set; }
        public Nullable<int> EXERCISE_TYPE_ID { get; set; }
        public string EXERCISE_DAY { get; set; }
        public string EXERCISE_NAME { get; set; }
        public Nullable<int> EXERCISE_REP_COUNT { get; set; }
        public string EXECISE_NOTE { get; set; }
        public string ROUTINE_ID { get; set; }
        public bool IS_ACTIVE { get; set; }
        public Nullable<int> EXERCISE_REP_ROUND { get; set; }
    }
}
