//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXERCISE_TYPE_TABLE
    {
        public int EXERCISE_TYPE_ID { get; set; }
        public string EXERCISE_TYPE_NAME { get; set; }
    }
}
