//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROUTINE_TABLE
    {
        public string ROUTINE_ID { get; set; }
        public string NAME_ROUTINE { get; set; }
        public string NOTE_ROUTINE { get; set; }
        public int USER_ID { get; set; }
        public System.DateTime CREATE_DATE_ROUTINE { get; set; }
        public bool IS_ACTIVE { get; set; }
    }
}
