//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_TABLE
    {
        public int UserID { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Identification { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
        public string ManagerName { get; set; }
        public Nullable<int> FKMB { get; set; }
        public string FKPAY { get; set; }
        public Nullable<int> FKROLE { get; set; }
        public Nullable<int> FKSITE { get; set; }
        public bool IS_ACTIVE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
    }
}
